### ISSUE TITLE
MaxPool with argmax 2d inaccuracies

### ISSUE THREAD

**Issue by attila-dusnoki-htec** [migraphx-benchmark/AMDMIGraphX#104]
Failing tests:

- test_maxpool_with_argmax_2d_precomputed_pads_cpu
- test_maxpool_with_argmax_2d_precomputed_strides_cpu

**Comment by attila-dusnoki-htec** [comment]
<details>
<summary>
FAIL: test_maxpool_with_argmax_2d_precomputed_pads_cpu (__main__.OnnxBackendNodeModelTest)
</summary>

```
======================================================================
FAIL: test_maxpool_with_argmax_2d_precomputed_pads_cpu (__main__.OnnxBackendNodeModelTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/onnx/backend/test/runner/__init__.py", line 290, in device_test_func
    return test_func(*args, device=device, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/onnx/backend/test/runner/__init__.py", line 467, in run
    self.assert_similar_outputs(
  File "../test/py/onnx_backend_test.py", line 47, in assert_similar_outputs
    np.testing.assert_equal(len(ref_outputs),
  File "/usr/local/lib/python3.8/dist-packages/numpy/testing/_private/utils.py", line 425, in assert_equal
    raise AssertionError(msg)
AssertionError: 
Items are not equal:

Program =
module: "main"
x = @param:x -> float_type, {1, 1, 5, 5}, {25, 25, 5, 1}, target_id=0
@1 = pooling[mode=max,padding={2, 2, 2, 2},padding_mode=0,stride={1, 1},lengths={5, 5},ceil_mode=0,lp_order=2,dyn_global=0](x) -> float_type, {1, 1, 5, 5}, {25, 25, 5, 1}, target_id=0
@2 = @return(@1), target_id=0


Compiled program =
module: "main"
@0 = check_context::migraphx::gpu::context  -> float_type, {}, {}, target_id=0
@1 = hip::hip_allocate_memory[shape=int8_type, {200}, {1},id=main:scratch] -> int8_type, {200}, {1}, target_id=0
@2 = load[offset=100,end=200](@1) -> float_type, {1, 1, 5, 5}, {25, 25, 5, 1}, target_id=0
x = @param:x -> float_type, {1, 1, 5, 5}, {25, 25, 5, 1}, target_id=0
@4 = hip::copy_to_gpu(x,@2) -> float_type, {1, 1, 5, 5}, {25, 25, 5, 1}, target_id=0
@5 = load[offset=0,end=100](@1) -> float_type, {1, 1, 5, 5}, {25, 25, 5, 1}, target_id=0
@6 = gpu::pooling[mode=max,padding={2, 2, 2, 2},padding_mode=0,stride={1, 1},lengths={5, 5},ceil_mode=0,lp_order=2,dyn_global=0](@4,@5) -> float_type, {1, 1, 5, 5}, {25, 25, 5, 1}, target_id=0
@7 = hip::copy_from_gpu(@6) -> float_type, {1, 1, 5, 5}, {25, 25, 5, 1}, target_id=0
@8 = hip::sync_stream(@7) -> float_type, {1, 1, 5, 5}, {25, 25, 5, 1}, target_id=0
@9 = @return(@8), target_id=0


 ACTUAL: 2
 DESIRED: 1

```

</details>

<details>
<summary>
FAIL: test_maxpool_with_argmax_2d_precomputed_strides_cpu (__main__.OnnxBackendNodeModelTest)
</summary>

```
======================================================================
FAIL: test_maxpool_with_argmax_2d_precomputed_strides_cpu (__main__.OnnxBackendNodeModelTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/onnx/backend/test/runner/__init__.py", line 290, in device_test_func
    return test_func(*args, device=device, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/onnx/backend/test/runner/__init__.py", line 467, in run
    self.assert_similar_outputs(
  File "../test/py/onnx_backend_test.py", line 47, in assert_similar_outputs
    np.testing.assert_equal(len(ref_outputs),
  File "/usr/local/lib/python3.8/dist-packages/numpy/testing/_private/utils.py", line 425, in assert_equal
    raise AssertionError(msg)
AssertionError: 
Items are not equal:

Program =
module: "main"
x = @param:x -> float_type, {1, 1, 5, 5}, {25, 25, 5, 1}, target_id=0
@1 = pooling[mode=max,padding={0, 0, 0, 0},padding_mode=0,stride={2, 2},lengths={2, 2},ceil_mode=0,lp_order=2,dyn_global=0](x) -> float_type, {1, 1, 2, 2}, {4, 4, 2, 1}, target_id=0
@2 = @return(@1), target_id=0


Compiled program =
module: "main"
@0 = check_context::migraphx::gpu::context  -> float_type, {}, {}, target_id=0
@1 = hip::hip_allocate_memory[shape=int8_type, {116}, {1},id=main:scratch] -> int8_type, {116}, {1}, target_id=0
@2 = load[offset=0,end=100](@1) -> float_type, {1, 1, 5, 5}, {25, 25, 5, 1}, target_id=0
x = @param:x -> float_type, {1, 1, 5, 5}, {25, 25, 5, 1}, target_id=0
@4 = hip::copy_to_gpu(x,@2) -> float_type, {1, 1, 5, 5}, {25, 25, 5, 1}, target_id=0
@5 = load[offset=100,end=116](@1) -> float_type, {1, 1, 2, 2}, {4, 4, 2, 1}, target_id=0
@6 = gpu::pooling[mode=max,padding={0, 0, 0, 0},padding_mode=0,stride={2, 2},lengths={2, 2},ceil_mode=0,lp_order=2,dyn_global=0](@4,@5) -> float_type, {1, 1, 2, 2}, {4, 4, 2, 1}, target_id=0
@7 = hip::copy_from_gpu(@6) -> float_type, {1, 1, 2, 2}, {4, 4, 2, 1}, target_id=0
@8 = hip::sync_stream(@7) -> float_type, {1, 1, 2, 2}, {4, 4, 2, 1}, target_id=0
@9 = @return(@8), target_id=0


 ACTUAL: 2
 DESIRED: 1

```

</details>

**Comment by attila-dusnoki-htec** [comment]
Pooling has an optional output: https://github.com/onnx/onnx/blob/main/docs/Changelog.md#outputs-1---2-8
Which contains the selected indecies.
