### ISSUE TITLE
Trilu inaccuracies

### ISSUE THREAD

**Issue by attila-dusnoki-htec** [migraphx-benchmark/AMDMIGraphX#124]
Failing tests:

- test_tril_cpu
- test_tril_one_row_neg_cpu
- test_tril_square_cpu

**Comment by attila-dusnoki-htec** [comment]
<details>
<summary>
FAIL: test_tril_cpu (__main__.OnnxBackendNodeModelTest)
</summary>

```
======================================================================
FAIL: test_tril_cpu (__main__.OnnxBackendNodeModelTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/onnx/backend/test/runner/__init__.py", line 290, in device_test_func
    return test_func(*args, device=device, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/onnx/backend/test/runner/__init__.py", line 467, in run
    self.assert_similar_outputs(
  File "../test/py/onnx_backend_test.py", line 59, in assert_similar_outputs
    np.testing.assert_allclose(ref_outputs[i],
  File "/usr/local/lib/python3.8/dist-packages/numpy/testing/_private/utils.py", line 1530, in assert_allclose
    assert_array_compare(compare, actual, desired, err_msg=str(err_msg),
  File "/usr/local/lib/python3.8/dist-packages/numpy/testing/_private/utils.py", line 844, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=0.001, atol=1e-05

Program =
module: "main"
@0 = @literal{ ... } -> int64_type, {4, 5}, {5, 1}, target_id=0
x = @param:x -> int64_type, {4, 5}, {5, 1}, target_id=0
@2 = mul(@0,x) -> int64_type, {4, 5}, {5, 1}, target_id=0
@3 = @return(@2), target_id=0


Compiled program =
module: "main"
@0 = check_context::migraphx::gpu::context  -> float_type, {}, {}, target_id=0
@1 = hip::hip_allocate_memory[shape=int8_type, {320}, {1},id=main:scratch] -> int8_type, {320}, {1}, target_id=0
@2 = hip::hip_copy_literal[id=main:@literal:0] -> float_type, {4, 5}, {5, 1}, target_id=0
x = @param:x -> int64_type, {4, 5}, {5, 1}, target_id=0
@4 = load[offset=160,end=320](@1) -> int64_type, {4, 5}, {5, 1}, target_id=0
@5 = hip::copy_to_gpu(x,@4) -> int64_type, {4, 5}, {5, 1}, target_id=0
@6 = load[offset=0,end=160](@1) -> int64_type, {4, 5}, {5, 1}, target_id=0
@7 = gpu::code_object[code_object=9560,symbol_name=convert_mul_convert_kernel,global=1024,local=1024,](@5,@2,@6) -> int64_type, {4, 5}, {5, 1}, target_id=0
@8 = hip::copy_from_gpu(@7) -> int64_type, {4, 5}, {5, 1}, target_id=0
@9 = hip::sync_stream(@8) -> int64_type, {4, 5}, {5, 1}, target_id=0
@10 = @return(@9), target_id=0


Mismatched elements: 4 / 20 (20%)
Max absolute difference: 8
Max relative difference: 0.
 x: array([[5, 0, 0, 0, 0],
       [9, 3, 0, 0, 0],
       [7, 6, 8, 0, 0],
       [6, 7, 7, 8, 0]])
 y: array([[0, 0, 0, 0, 0],
       [9, 0, 0, 0, 0],
       [7, 6, 0, 0, 0],
       [6, 7, 7, 0, 0]], dtype=int64)

```

</details>

<details>
<summary>
FAIL: test_tril_one_row_neg_cpu (__main__.OnnxBackendNodeModelTest)
</summary>

```
======================================================================
FAIL: test_tril_one_row_neg_cpu (__main__.OnnxBackendNodeModelTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/onnx/backend/test/runner/__init__.py", line 290, in device_test_func
    return test_func(*args, device=device, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/onnx/backend/test/runner/__init__.py", line 467, in run
    self.assert_similar_outputs(
  File "../test/py/onnx_backend_test.py", line 59, in assert_similar_outputs
    np.testing.assert_allclose(ref_outputs[i],
  File "/usr/local/lib/python3.8/dist-packages/numpy/testing/_private/utils.py", line 1530, in assert_allclose
    assert_array_compare(compare, actual, desired, err_msg=str(err_msg),
  File "/usr/local/lib/python3.8/dist-packages/numpy/testing/_private/utils.py", line 844, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=0.001, atol=1e-05

Program =
module: "main"
@0 = @literal{0, 0, 0, 0, 0} -> int64_type, {1, 5}, {5, 1}, target_id=0
x = @param:x -> int64_type, {3, 1, 5}, {5, 5, 1}, target_id=0
@2 = multibroadcast[out_lens={3, 1, 5},out_dyn_dims={}](@0) -> int64_type, {3, 1, 5}, {0, 5, 1}, target_id=0
@3 = mul(@2,x) -> int64_type, {3, 1, 5}, {5, 5, 1}, target_id=0
@4 = @return(@3), target_id=0


Compiled program =
module: "main"
@0 = check_context::migraphx::gpu::context  -> float_type, {}, {}, target_id=0
x = @param:x -> int64_type, {3, 1, 5}, {5, 5, 1}, target_id=0
@2 = hip::hip_copy_literal[id=main:@literal:0] -> int64_type, {3, 1, 5}, {5, 5, 1}, target_id=0
@3 = hip::copy_from_gpu(@2) -> int64_type, {3, 1, 5}, {5, 5, 1}, target_id=0
@4 = hip::sync_stream(@3) -> int64_type, {3, 1, 5}, {5, 5, 1}, target_id=0
@5 = @return(@4), target_id=0


Mismatched elements: 3 / 15 (20%)
Max absolute difference: 9
Max relative difference: inf
 x: array([[[5, 0, 0, 0, 0]],

       [[9, 0, 0, 0, 0]],...
 y: array([[[0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0]],...

```

</details>

<details>
<summary>
FAIL: test_tril_square_cpu (__main__.OnnxBackendNodeModelTest)
</summary>

```
======================================================================
FAIL: test_tril_square_cpu (__main__.OnnxBackendNodeModelTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/onnx/backend/test/runner/__init__.py", line 290, in device_test_func
    return test_func(*args, device=device, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/onnx/backend/test/runner/__init__.py", line 467, in run
    self.assert_similar_outputs(
  File "../test/py/onnx_backend_test.py", line 59, in assert_similar_outputs
    np.testing.assert_allclose(ref_outputs[i],
  File "/usr/local/lib/python3.8/dist-packages/numpy/testing/_private/utils.py", line 1530, in assert_allclose
    assert_array_compare(compare, actual, desired, err_msg=str(err_msg),
  File "/usr/local/lib/python3.8/dist-packages/numpy/testing/_private/utils.py", line 844, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=0.001, atol=1e-05

Program =
module: "main"
@0 = @literal{0, 0, 0, 1, 0, 0, 1, 1, 0} -> int64_type, {3, 3}, {3, 1}, target_id=0
x = @param:x -> int64_type, {2, 3, 3}, {9, 3, 1}, target_id=0
@2 = multibroadcast[out_lens={2, 3, 3},out_dyn_dims={}](@0) -> int64_type, {2, 3, 3}, {0, 3, 1}, target_id=0
@3 = mul(@2,x) -> int64_type, {2, 3, 3}, {9, 3, 1}, target_id=0
@4 = @return(@3), target_id=0


Compiled program =
module: "main"
@0 = check_context::migraphx::gpu::context  -> float_type, {}, {}, target_id=0
@1 = hip::hip_allocate_memory[shape=int8_type, {288}, {1},id=main:scratch] -> int8_type, {288}, {1}, target_id=0
@2 = hip::hip_copy_literal[id=main:@literal:0] -> float_type, {3, 3}, {3, 1}, target_id=0
x = @param:x -> int64_type, {2, 3, 3}, {9, 3, 1}, target_id=0
@4 = load[offset=144,end=288](@1) -> int64_type, {2, 3, 3}, {9, 3, 1}, target_id=0
@5 = hip::copy_to_gpu(x,@4) -> int64_type, {2, 3, 3}, {9, 3, 1}, target_id=0
@6 = load[offset=0,end=144](@1) -> int64_type, {2, 3, 3}, {9, 3, 1}, target_id=0
@7 = multibroadcast[out_lens={2, 3, 3},out_dyn_dims={}](@2) -> float_type, {2, 3, 3}, {0, 3, 1}, target_id=0
@8 = gpu::code_object[code_object=9560,symbol_name=convert_mul_convert_kernel,global=1024,local=1024,](@5,@7,@6) -> int64_type, {2, 3, 3}, {9, 3, 1}, target_id=0
@9 = hip::copy_from_gpu(@8) -> int64_type, {2, 3, 3}, {9, 3, 1}, target_id=0
@10 = hip::sync_stream(@9) -> int64_type, {2, 3, 3}, {9, 3, 1}, target_id=0
@11 = @return(@10), target_id=0


Mismatched elements: 6 / 18 (33.3%)
Max absolute difference: 8
Max relative difference: 0.
 x: array([[[5, 0, 0],
        [3, 7, 0],
        [3, 5, 2]],...
 y: array([[[0, 0, 0],
        [3, 0, 0],
        [3, 5, 0]],...

```

</details>
