### ISSUE TITLE
Split failures

### ISSUE THREAD

**Issue by attila-dusnoki-htec** [migraphx-benchmark/AMDMIGraphX#132]
Failing tests:
- test_split_1d_uneven_split_opset18_cpu
- test_split_2d_uneven_split_opset18_cpu

**Comment by attila-dusnoki-htec** [comment]
<details>
<summary>
ERROR: test_split_1d_uneven_split_opset18_cpu (__main__.OnnxBackendNodeModelTest)
</summary>

```
======================================================================
ERROR: test_split_1d_uneven_split_opset18_cpu (__main__.OnnxBackendNodeModelTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/onnx/backend/test/runner/__init__.py", line 290, in device_test_func
    return test_func(*args, device=device, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/onnx/backend/test/runner/__init__.py", line 382, in run
    prepared_model = self.backend.prepare(model, device)
  File "/code/AMDMIGraphX/build/lib/onnx_migraphx/backend.py", line 125, in prepare
    return cls.prepare(bin, device, **kwargs)
  File "/code/AMDMIGraphX/build/lib/onnx_migraphx/backend.py", line 112, in prepare
    inf = migraphx.parse_onnx_buffer(model)
RuntimeError: /code/AMDMIGraphX/src/onnx/parse_split.cpp:74: parse: PARSE_SPLIT: input cannot be equally divided into 4 splits!
```

</details>

<details>
<summary>
ERROR: test_split_2d_uneven_split_opset18_cpu (__main__.OnnxBackendNodeModelTest)
</summary>

```
======================================================================
ERROR: test_split_2d_uneven_split_opset18_cpu (__main__.OnnxBackendNodeModelTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/onnx/backend/test/runner/__init__.py", line 290, in device_test_func
    return test_func(*args, device=device, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/onnx/backend/test/runner/__init__.py", line 382, in run
    prepared_model = self.backend.prepare(model, device)
  File "/code/AMDMIGraphX/build/lib/onnx_migraphx/backend.py", line 125, in prepare
    return cls.prepare(bin, device, **kwargs)
  File "/code/AMDMIGraphX/build/lib/onnx_migraphx/backend.py", line 112, in prepare
    inf = migraphx.parse_onnx_buffer(model)
RuntimeError: /code/AMDMIGraphX/src/onnx/parse_split.cpp:74: parse: PARSE_SPLIT: input cannot be equally divided into 3 splits!
```

</details>
